name: deploy

on:
  push:
    branches: [master]

jobs:
  deployToAws:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          USERNAME: ubuntu
          HOST: ${{ secrets.HOST }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: whoami
